server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: 1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
      

  
  
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 571912387241-1o3o3jefnme9cpft2vgae50mlop70jgu.apps.googleusercontent.com
            client-secret: Qzi-UGG1xLAD0rpcHIWAHtRo
            scope:
            - email
            - profile
            
          facebook:
            client-id: DONT
            client-secret: 571912387241 
            scope: 
            - email
            - public_profile       


          kakao:
            authorization-grant-type: authorization_code
            client-id: e3c6858cb343797f622d6a4a216f6341
            client-secret: lO55iCnU5ku9BhIMJIuMv6oYUYEXEQZV
            redirect-uri: http://localhost:8000/login/oauth2/code/kakao
            scope: 
            - profile
            - account_email
            client-authentication-method: POST
            client-name: Kakao
                
          naver:
            client-id: zkY3Ny0lw0mM65WL8Sv5
            client-secret: gOiNFMRpRr
            scope: 
            - name
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver   
            
            
            
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id      
  
  
  
  
  
  
      
      
      